### ISSUE TITLE
Window scrolling?

### ISSUE THREAD

**Issue by sardaukar** [SamualLB/ncurses#10]
Is it possible to use `scrollok` with these bindings?

**Comment by SamualLB** [comment]
Added in v0.0.7

**Comment by sardaukar** [comment]
Thanks!

**Comment by sardaukar** [comment]
Is there like a guide for Lib writing that is better than the original docs? I'd like to add the remaining `scroll` related functions (all functions, actually!) but I find it very hard to figure out.
