### ISSUE TITLE
Verbatim "Hello world" example is not printing text

### ISSUE THREAD

**Issue by C-Dev777** [SamualLB/ncurses#12]
I've been trying to get the hello world example working. All dependencies are satisfied, the shard.yml file has been run. The file I have is "main.cr", and -aside from the text to print- is verbatim to the example provided. This is what it looks like:

```
require "ncurses"

NCurses.start
NCurses.print "Hi\n"
NCurses.end
```

When I run this the program compiles without warnings or error messages, but no text is printed. I tried this in both the integrated VS Code terminal and the OS terminal, the result is the same.

Was there a recent change in the ncurses binary or is it a problem on my side?

Current operating system: Linux Mint 19.2 Cinnamon.

Crystal version: Crystal 0.32.1
LLVM version: 8.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by SamualLB** [comment]
To make sure this is displayed, make sure you call `NCurses.refresh`. This code will also exit immediatly so you still probably won't see anything.

This is the most basic example:
```crystal
require "ncurses"

NCurses.start

NCurses.print "Hi"
NCurses.refresh
NCurses.get_char

NCurses.end
```
